#Start with a base image containing Java runtime
FROM openjdk:8-slim as build

#Information around who maintains the image
MAINTAINER Wasim Ansari

# Add the application's jar to the container
COPY target/SimpleApp-0.0.1-SNAPSHOT.jar SimpleApp-0.0.1-SNAPSHOT.jar

#execute the application
ENTRYPOINT ["java","-jar","/SimpleApp-0.0.1-SNAPSHOT.jar"]